### ISSUE TITLE
[BUG] Crash when disabling/deleting instance

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion-module-bmd-hyperdeck#64] opened 2022-02-14 11:08 UTC
When an instance is enabled and is attempting to connect to an IP that isn't a hyperdeck (in this case it was an unreachable IP due to different subnet and no routing) it crashes Companion when attempting to disable or delete the instance.

```
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.20:9993
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
Emitted 'error' event on Hyperdeck instance at:
    at Socket.<anonymous> (C:\Users\jeff\workspace\companion\node_modules\hyperdeck-connection\dist\hyperdeck.js:53:45)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.20',
  port: 9993
}
```

**Comment by sphlabs** [comment] 2022-02-14 11:42
Duplicate of #28

**Closed by sphlabs** 2022-02-14 11:42 UTC
