### ISSUE TITLE
Issue $(hyperdeck:countdownTimecodeHMS) displaying --:--:--:--

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-hyperdeck#108] opened 2023-10-26 14:44 UTC
v3.2.0+6439. The variable $(hyperdeck:countdownTimecodeHMS) displays --:--:--:-- in preview mode. In playback mode it ia working as expected. It should provide countdown timecode, regardless the hyperdeck status (as before).

Regards, Nico Wasmus

**Comment by sphlabs** [comment] 2024-03-09 19:24
This is a duplicate of #109 and a fix is in-progress.

**Closed by sphlabs** 2024-03-09 19:24 UTC

**Comment by LikeThisReview** [comment] 2024-03-10 14:58
Ok, thanks for the update.

Op za 9 mrt 2024 om 20:25 schreef Stephen Harrison ***@***.***
