### ISSUE TITLE
Support playoutbee possible?

### ISSUE THREAD

**Issue by Bascht74** [bitfocus/companion-module-bmd-hyperdeck#68] opened 2022-05-05 23:46 UTC
Hi, 

would it be possible to support playoutbee?
( https://playoutbee.com/ )

Cheers, 

sebastian

**Comment by sphlabs** [comment] 2022-05-06 02:43
In theory, playoutbee should already work, since it supports the hyperdeck protocol. But I don't have a copy of PlayoutBee to test so can't confirm this, or workout why it doesn't work if that seems to be the case.

However, there is also a dedicated PlayoutBee companion module, so I am not sure it is is necessary to support it through the hyperdeck module? Perhaps there is a use case I am not thinking of?

**Comment by Bascht74** [comment] 2022-05-06 23:15
Hi @sphlabs , first at all, thanks for your quick answer. 

As I have three licences I could send you one installation file (e.g. for Windows) so you could try. 

But it might be maybe possible without it according to the logs:
```
22.05.07 00:53:21 instance(hyperdeck): Slot 2 recording time parse error: RangeError: Invalid time value
22.05.07 00:53:21 instance(hyperdeck): Slot 1 recording time parse error: RangeError: Invalid time value
22.05.07 00:53:21 instance(hyperdeck): Connection error - 200 ok
22.05.07 00:53:10 instance(hyperdeck): Slot 2 recording time parse error: RangeError: Invalid time value
22.05.07 00:53:10 instance(hyperdeck): Slot 1 recording time parse error: RangeError: Invalid time value
22.05.07 00:53:10 instance(hyperdeck): Connection error - 200 ok
```
It seams that you just need to disable the recording section in you module as this causes reconnections every 10 seconds.

> Perhaps there is a use case I am not thinking of?
Yes! In those 10 second sections I can set the play speed with your module (e.g. 90% or 110%) and it works great!
That is not possible with the other module. As I have one hyperdeck, too, it would be nice just to use one integration for both.
So would it be possible to add a configuration/type without recording?

Sebastian

**Comment by sphlabs** [comment] 2022-11-03 23:55
It seems more logical that, since there is a specific module for playoutbee that is tailored just for that software, it would be more logical to request the missing features be added to that module; rather than adding special cases into the Hyperdeck module to accommodate it.

I don’t see any issues from you requesting this on the playoutbee issue queue, so maybe that would be worth trying.

I am reluctant to start coding in support for non-Blackmagic devices. Although it is intended to support the Hyperdeck protocol it is clearly only a subset, and, especially given that the protocol is not as thoroughly documented as it could be, it is likely that there would be (now or in the future) implementation differences that cause unexpected behaviour.

**Comment by sphlabs** [comment] 2023-02-06 22:03
Just to add to my previous comment; what seems to be happening, and the reason that you are seeing those error messages, is that playoutbee is returning the `'recording time':` variable in response to a `transport info` request, but that the value is not a valid, expected value (number of seconds remaining).

If that is the case -- if, because I can't verify this without running tests on a playoutbee device -- then it is not correctly emulating the HyperDeck API in this instance. If playoutbee simply didn't return `'recording time'` at all then I don't think you would be seeing these errors.

So, as things stand, I won't be adding specific support for playoutbee. I still thing your best approach to get the features you want would be to request that they be added to the playoutbee module itself.

**Closed by sphlabs** 2023-02-06 22:03 UTC
