### ISSUE TITLE
Javascript crash when Hyperdeck is off

### ISSUE THREAD

**Issue by mikecreates86** [bitfocus/companion-module-bmd-hyperdeck#24] opened 2020-08-02 00:15 UTC
Whenever my HyperDeck is off, with the instance enabled, I get a Javascript crash repeatedly. This is an issue as it's often not turned on (one of the things my Stream Deck does is power cycle all the gear on). I can understand it having minor issues with the hardware off but it shouldn't crash. Here's a screenshot of what I'm seeing.

Other users on the Facebook group [have commented on this too](https://www.facebook.com/groups/companion/2640990672785933/?comment_id=2641173802767620&reply_comment_id=2642192942665706&notif_id=1596206595921662&notif_t=group_comment).

![Screenshot Media MacBook Pro 2020-07-31 at 10 14 41](https://user-images.githubusercontent.com/69094941/89112648-bb5bd600-d433-11ea-99b4-c05f09986658.png)

**Comment by baltedewit** [comment] 2020-08-05 08:46
Thanks for the report. Initial static analysis shows the error handling is correct in all places, so I'm quite surprised by this. I'm out of office this week, so I can't look into this further right now.

**Comment by krocheck** [comment] 2020-08-05 08:59
@baltedewit my best guess is that the initial connect call in [`connect(...)`](https://github.com/nrkno/tv-automation-hyperdeck-connection/blob/1f40a503f0dc076fdce358b9815e06758d57269c/src/hyperdeck.ts#L102) is missing a try-catch wrapper.  It has one down in [`_retryConnection()`](https://github.com/nrkno/tv-automation-hyperdeck-connection/blob/1f40a503f0dc076fdce358b9815e06758d57269c/src/hyperdeck.ts#L156) but not there

**Comment by baltedewit** [comment] 2020-08-05 09:27
Yes, _something_ of that nature is my best bet right now too. The documentation however states it can all be handled through the `.on('error', ...)` handler so I think I need to do some trial and error first

**Comment by sphlabs** [comment] 2020-10-02 14:48
Trying to recreate this, I get the `.on('error', …)` error messages in the log, but I don't get the crash of the OP.

However, it occurs to me that a failed connection maybe shouldn't be throwing repeated error messages anyway. I would say it should be, at the most, a warning and maybe only a debug message. Looking at some other modules, there doesn't appear to be a consistent approach to this--e.g. octopus reports errors, but ATEM doesn't report anything at all.

Is there official guidance on the severity of a failed connection, in terms of logging?

**Comment by sphlabs** [comment] 2021-02-19 13:37
Duplicate of #28

**Closed by sphlabs** 2021-02-19 13:37 UTC
Labels: bug
